### ISSUE TITLE
mobile/small window tweaks

### ISSUE THREAD

**Issue by creesch** [toolbox-team/reddit-moderator-toolbox#95]
Toolbox works on mobile Firefox and I often check some things on my phone. This made me aware of some things we probably can fox fairly easily without having to refactor much.

- popups in new modmail fall outside the window. This can be fixed by having css for a screenwidth under a certain amount of pixels that makes the popups act more like overlays by setting the left and right values to zero.
- When opening the new modmail user sidebar it doesn't have toolbox buttons. 
- popups can not be dragged as our dragging plugin doesn't work with touch.
- a full modbar becomes distorted.

From a quick test it seems that new modmail starts morphing to a mobile oriented layout from 768 pixels and lower, so that is what I'll target at as well I guess.

**Comment by creesch** [comment]
Quick and dirty fixes for popups on smaller screens 

```css
@media screen and (max-width: 768px) {
  .mod-toolbox-rd .tb-popup {
    left: 0 !important;
    right: 0 !important;
    top: 0 !important;
    position: fixed !important;
  }

  .mod-toolbox-rd .tb-popup .tb-popup-content {
    min-width: 0 !important;
    max-height: calc(100vh - 105px) !important;
  }
  .mod-toolbox-rd #tb-toolbarshortcuts {
    display: none !important
  }
  .mod-toolbox-rd .utagger-type-list td {
    display: inline;
    height: 15px;
    line-height: 30px;
  }  
}
```

**Comment by creesch** [comment]
Today I was reminded about this and did some updated work on the css

```css
@media screen and (max-width: 768px) {
    .mod-toolbox-rd.mod-toolbox-rd .tb-window-wrapper.tb-window-wrapper {
        top: 0;
        bottom: 0 !important;
        left: 0;
        right: 0;
        margin-bottom: 0;
        postion: fixed !important;
    }
    
    .mod-toolbox-rd .tb-profile-sidebar {
        display: none;
    }

    .mod-toolbox-rd .tb-profile-overlay .tb-window-tabs-wrapper {
        width: 100%;
        max-height: calc(100vh - 105px) !important;
        overflow: auto;
    }

    .mod-toolbox-rd .tb-page-overlay {
        padding: 0 !important;

    }
    .mod-toolbox-rd .tb-popup {
        left: 0 !important;
        right: 0 !important;
        top: 0 !important;
        position: fixed !important;
    }

    .mod-toolbox-rd .tb-popup .tb-popup-content {
        min-width: 0 !important;
        max-height: calc(100vh - 105px);
    }

}
```
